logger function was added to all scripts, script get_mnp_web_service_call_count was developed

diff --git a/deployment/templates/get_delta_of_last1h_sim_card_count.sh.j2 b/deployment/templates/get_delta_of_last1h_sim_card_count.sh.j2
--- a/deployment/templates/get_delta_of_last1h_sim_card_count.sh.j2
+++ b/deployment/templates/get_delta_of_last1h_sim_card_count.sh.j2
@@ -1,4 +1,10 @@
 #!/bin/bash
+#
+# This script is part of Rightel Portability Monitoring Project at Tookasoft
+# April 2017
+#
+# Developer: Ramin Sharafkandi
+# Head of Team: Hamed Shakiba
 
 MYSQL_USERNAME={{ mysql.user }}
 MYSQL_PASSWORD={{ mysql.password }}
@@ -7,54 +13,68 @@ MYSQL_SCHEMA={{ mysql.schema }}
 MODE="positive"
 DEBUG_MODE="False"
 DEBUG_LOG="/tmp/zabbix_mnp_monitoring.log"
+SCRIPT_NAME=$( basename $0 )
+
+logger() {
+  log_date_time=$( date +"%a %x %X" )
+  echo "$log_date_time - $SCRIPT_NAME - $@" >>$DEBUG_LOG
+}
+
+[ $DEBUG_MODE == "True" ] && logger "script called with these arguments: $@"
 
 while [ True ]; do
 
    [ -z "$1" ] && break
-   [ $DEBUG_MODE == "True" ] && echo "$0 : Processing argument $1" >>$DEBUG_LOG
 
    case "$1" in
      "-u" | "--username" )
         shift
-        [ -z "$1" ] && echo "ERROR! -u/--user must be followed by username" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -u/--user must be followed by username"
+        [ -z "$1" ] && exit 1
         MYSQL_USERNAME=$1
         shift
         ;;
      "-p" | "--password" )
         shift
-        [ -z "$1" ] && echo "ERROR! -p/--password must be followed by password" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -p/--password must be followed by password"
+        [ -z "$1" ] && exit 1
         MYSQL_PASSWORD=$1
         shift
         ;;
      "-h" | "--hostname" )
         shift
-        [ -z "$1" ] && echo "ERROR! -h/--host must be followed by hostname" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -h/--host must be followed by hostname"
+        [ -z "$1" ] && exit 1
         MYSQL_HOSTNAME=$1
         shift
         ;;
      "-s" | "--schema" )
         shift
-        [ -z "$1" ] && echo "ERROR! -s/--schema must be followed by schema name" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -s/--schema must be followed by schema name"
+        [ -z "$1" ] && exit 1
         MYSQL_SCHEMA=$1
         shift
         ;;
      "-m" | "--mode" )
         shift
-        [ -z "$1" ] && echo "ERROR! -m/--mode must be followed by a mode name (ie. positive or negative)" && exit 1
-        [ "$1" != "positive" -a "$1" != "negative" ] && echo "ERROR! Invalid mode: $1" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && echo "ERROR! -m/--mode must be followed by a mode name (ie. positive or negative)"
+        [ -z "$1" ] && exit 1
+        [ "$1" != "positive" -a "$1" != "negative" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! Invalid mode: $1"
+        [ "$1" != "positive" -a "$1" != "negative" ] && exit 1
         MODE=$1
         shift
         ;;
      "--help" )
-        echo "Usage $0 [-u|--username USERNAME] [-p|--password PASSWORD] [-h|--hostname HOSTNAME] [-s|--schema SCHEMANAME]"
+        echo "Usage $0 [-u|--username USERNAME] [-p|--password PASSWORD] [-h|--hostname HOSTNAME] [-s|--schema SCHEMANAME] [-m|--mode positive|negative]"
         echo
-        echo "   This script runs a query against mysql database to get count of users whith -1 status who have entered"
-        echo "their numbers but still have not confirmed the process"
+        echo "   This script runs a query against mysql database to get difference between entries with status=4 of this hour"
+        echo "comparing with entries with status=4 of the same hour yesterday."
+        echo "   Entries with status=4 denote issued SIM cards."
         echo
         exit 0
         ;;
      * )
-        echo "ERROR! Invalid argument: $1"
+        [ $DEBUG_MODE == "True" ] && logger "ERROR! Invalid argument: $1"
         exit 1
         ;;
    esac
@@ -67,19 +87,19 @@ today_end_date=`date --date="today" +"%Y-%m-%d ${prev_hour}:59:59"`
 yesterday_start_date=`date --date="yesterday" +"%Y-%m-%d ${prev_hour}:00:00"`
 yesterday_end_date=`date --date="yesterday" +"%Y-%m-%d ${prev_hour}:59:59"`
 
-[ $DEBUG_MODE == "True" ] && echo "$0 : /usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA}" >>$DEBUG_LOG
-[ $DEBUG_MODE == "True" ] && echo "$0 : select count(*) from mnp_requestinfolog where status = 4 and createDate between '${today_start_date}' and '${today_end_date}'"  >>$DEBUG_LOG
-[ $DEBUG_MODE == "True" ] && echo "$0 : select count(*) from mnp_requestinfolog where status = 4 and createDate between '${yesterday_start_date}' and '${yesterday_end_date}'" >>$DEBUG_LOG
+[ $DEBUG_MODE == "True" ] && logger "/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA}"
+[ $DEBUG_MODE == "True" ] && logger "select count(*) from mnp_requestinfolog where status = 4 and createDate between '${today_start_date}' and '${today_end_date}'"
+[ $DEBUG_MODE == "True" ] && logger "select count(*) from mnp_requestinfolog where status = 4 and createDate between '${yesterday_start_date}' and '${yesterday_end_date}'"
 
 result=`
-/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA} << EOF1:
+/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA} 2>&1 << EOF1:
 select
 ( select count(*) from mnp_requestinfolog where status = 4 and createDate between '${today_start_date}' and '${today_end_date}' ) -
 ( select count(*) from mnp_requestinfolog where status = 4 and createDate between '${yesterday_start_date}' and '${yesterday_end_date}' );
 EOF1:
 `
 
-[ $DEBUG_MODE == "True" ] && echo "$0 : result is $result"  >>$DEBUG_LOG
+[ $DEBUG_MODE == "True" ] && logger "result is $result"
 
 if [ "$MODE" == "positive" ]; then
   if [ "$result" -ge 0 ]; then
diff --git a/deployment/templates/get_mnp_web_service_call_count.sh.j2 b/deployment/templates/get_mnp_web_service_call_count.sh.j2
--- a/deployment/templates/get_mnp_web_service_call_count.sh.j2
+++ b/deployment/templates/get_mnp_web_service_call_count.sh.j2
@@ -10,7 +10,7 @@ MYSQL_USERNAME={{ mysql.user }}
 MYSQL_PASSWORD={{ mysql.password }}
 MYSQL_HOSTNAME={{ mysql.host }}
 MYSQL_SCHEMA={{ mysql.schema }}
-WHEN="today"
+WEB_SERVICE_NAME=""
 DEBUG_MODE="False"
 DEBUG_LOG="/tmp/zabbix_mnp_monitoring.log"
 SCRIPT_NAME=$( basename $0 )
@@ -50,25 +50,23 @@ while [ True ]; do
         ;;
      "-s" | "--schema" )
         shift
-        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -s/--schema must be followed by schema name"
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -h/--host must be followed by hostname"
         [ -z "$1" ] && exit 1
         MYSQL_SCHEMA=$1
         shift
         ;;
-     "-w" | "--when" )
+     "-w" | "--webservice" )
         shift
-        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -w/--when must be followed by a date expression (ie today/yesterday ..)"
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -w/--webservice must be followed by a web service name"
         [ -z "$1" ] && exit 1
-        WHEN=$( echo $1 | tr [:upper:] [:lower:] )
-        [ "$WHEN" != "today" -a "$WHEN" != "yesterday" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! Invalid mode: $WHEN"
-        [ "$WHEN" != "today" -a "$WHEN" != "yesterday" ] && exit 1
+        WEB_SERVICE_NAME=$( echo "$1" | tr [:upper:] [:lower:] )
         shift
         ;;
      "--help" )
-        echo "Usage $0 [-u|--username USERNAME] [-p|--password PASSWORD] [-h|--hostname HOSTNAME] [-s|--schema SCHEMANAME] [-w|--when today|yesterday]"
+        echo "Usage $0 [-u|--username USERNAME] [-p|--password PASSWORD] [-h|--hostname HOSTNAME] [-s|--schema SCHEMANAME]"
         echo
-        echo "   This script runs a query against mysql database to get count of registered portability requests of current hour or the same hour of yesterday"
-        echo "depending on the value of --when parameter (by default it is today)."
+        echo "   This script runs a query against mysql database to get count of call of the webservice whose name is passed to script"
+        echo "during last 30 minutes."
         echo
         exit 0
         ;;
@@ -80,16 +78,22 @@ while [ True ]; do
 
 done
 
-prev_hour=`date --date="1 hour ago" +"%H"`
-start_date=`date --date="$WHEN" +"%Y-%m-%d ${prev_hour}:00:00"`
-end_date=`date --date="$WHEN" +"%Y-%m-%d ${prev_hour}:59:59"`
+if [ -z "$WEB_SERVICE_NAME" ]; then
+  [ $DEBUG_MODE == "True" ] && logger "ERROR: No web-service name was passed to script"
+  exit 1
+fi
+
+start_date=`date --date="-30 minutes" +"%Y-%m-%d %H:%M:%S"`
+end_date=`date +"%Y-%m-%d %H:%M:%S"`
 
 [ $DEBUG_MODE == "True" ] && logger "/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA}"
-[ $DEBUG_MODE == "True" ] && logger "select count(*) from mnp_requestinfolog where status = 4 and createDate between '${start_date}' and '${end_date}'"
+[ $DEBUG_MODE == "True" ] && logger "select count(*) from mnp_webservicelog where status = 0 and webServiceName = '${WEB_SERVICE_NAME}' and requestDate between '${start_date}' and '${end_date}'"
+
 result=`
 /usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA} 2>&1 << EOF1:
-select count(*) from mnp_requestinfolog where status = 1 and createDate between '${start_date}' and '${end_date}';
+select count(*) from mnp_webservicelog where status = 0 and webServiceName = '${WEB_SERVICE_NAME}' and requestDate between '${start_date}' and '${end_date}'";
 EOF1:
 `
+
 [ $DEBUG_MODE == "True" ] && logger "result is $result"
 echo "$result"
diff --git a/deployment/templates/get_sim_card_daily_count.sh.j2 b/deployment/templates/get_sim_card_daily_count.sh.j2
--- a/deployment/templates/get_sim_card_daily_count.sh.j2
+++ b/deployment/templates/get_sim_card_daily_count.sh.j2
@@ -1,4 +1,10 @@
 #!/bin/bash
+#
+# This script is part of Rightel Portability Monitoring Project at Tookasoft
+# April 2017
+#
+# Developer: Ramin Sharafkandi
+# Head of Team: Hamed Shakiba
 
 MYSQL_USERNAME={{ mysql.user }}
 MYSQL_PASSWORD={{ mysql.password }}
@@ -7,53 +13,67 @@ MYSQL_SCHEMA={{ mysql.schema }}
 WHEN="today"
 DEBUG_MODE="False"
 DEBUG_LOG="/tmp/zabbix_mnp_monitoring.log"
+SCRIPT_NAME=$( basename $0 )
+
+logger() {
+  log_date_time=$( date +"%a %x %X" )
+  echo "$log_date_time - $SCRIPT_NAME - $@" >>$DEBUG_LOG
+}
+
+[ $DEBUG_MODE == "True" ] && logger "script called with these arguments: $@"
 
 while [ True ]; do
 
    [ -z "$1" ] && break
-   [ $DEBUG_MODE == "True" ] && echo "$0 : Processing argument $1" >>$DEBUG_LOG
 
    case "$1" in
      "-u" | "--username" )
         shift
-        [ -z "$1" ] && echo "ERROR! -u/--user must be followed by username" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -u/--user must be followed by username"
+        [ -z "$1" ] && exit 1
         MYSQL_USERNAME=$1
         shift
         ;;
      "-p" | "--password" )
         shift
-        [ -z "$1" ] && echo "ERROR! -p/--password must be followed by password" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -p/--password must be followed by password"
+        [ -z "$1" ] && exit 1
         MYSQL_PASSWORD=$1
         shift
         ;;
      "-h" | "--hostname" )
         shift
-        [ -z "$1" ] && echo "ERROR! -h/--host must be followed by hostname" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -h/--host must be followed by hostname"
+        [ -z "$1" ] && exit 1
         MYSQL_HOSTNAME=$1
         shift
         ;;
      "-s" | "--schema" )
         shift
-        [ -z "$1" ] && echo "ERROR! -s/--schema must be followed by schema name" && exit 1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -h/--host must be followed by hostname"
+        [ -z "$1" ] && exit 1
         MYSQL_SCHEMA=$1
         shift
         ;;
      "-w" | "--when" )
         shift
-        [ -z "$1" ] && echo "ERROR! -w/--when must be followed by a date expression (ie today/yesterday ..)" && exit 1
-        WHEN=$1
+        [ -z "$1" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! -w/--when must be followed by a date expression (ie today/yesterday ..)"
+        [ -z "$1" ] && exit 1
+        WHEN=$( echo $1 | tr [:upper:] [:lower:] )
+        [ "$WHEN" != "today" -a "$WHEN" != "yesterday" ] && [ $DEBUG_MODE == "True" ] && logger "ERROR! Invalid mode: $WHEN"
+        [ "$WHEN" != "today" -a "$WHEN" != "yesterday" ] && exit 1
         shift
         ;;
      "--help" )
         echo "Usage $0 [-u|--username USERNAME] [-p|--password PASSWORD] [-h|--hostname HOSTNAME] [-s|--schema SCHEMANAME]"
         echo
-        echo "   This script runs a query against mysql database to get count of users whith -1 status who have entered"
-        echo "their numbers but still have not confirmed the process"
+        echo "   This script runs a query against mysql database to get count of entries with status=4 ie. no. of issued SIM cards during today"
+        echo "or yesterday depending on --when parameter (by default is today)"
         echo
         exit 0
         ;;
      * )
-        echo "ERROR! Invalid argument: $1"
+        [ $DEBUG_MODE == "True" ] && logger "ERROR! Invalid argument: $1"
         exit 1
         ;;
    esac
@@ -63,12 +83,14 @@ done
 start_date=`date --date="$WHEN" +"%Y-%m-%d 01:0:01"`
 end_date=`date --date="$WHEN" +"%Y-%m-%d 22:59:59"`
 
-[ $DEBUG_MODE == "True" ] && echo "$0 : /usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA}" >>$DEBUG_LOG
-[ $DEBUG_MODE == "True" ] && echo "$0 : select count(*) from mnp_requestinfolog where status = 4 and createDate between '${start_date}' and '${end_date}'" >>$DEBUG_LOG
+[ $DEBUG_MODE == "True" ] && logger "/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA}"
+[ $DEBUG_MODE == "True" ] && logger "select count(*) from mnp_requestinfolog where status = 4 and createDate between '${start_date}' and '${end_date}'"
+
 result=`
-/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA} << EOF1:
+/usr/bin/mysql -sN -u ${MYSQL_USERNAME} --password=${MYSQL_PASSWORD} -h ${MYSQL_HOSTNAME} ${MYSQL_SCHEMA} 2>&1 << EOF1:
 select count(*) from mnp_requestinfolog where status = 4 and createDate between '${start_date}' and '${end_date}';
 EOF1:
 `
-[ $DEBUG_MODE == "True" ] && echo "$0 : result is $result" >>$DEBUG_LOG
+
+[ $DEBUG_MODE == "True" ] && logger "result is $result"
 echo "$result"
